# Generated by Django 5.1 on 2024-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='device_type',
            field=models.CharField(choices=[('model_a', 'Model A'), ('model_b', 'Model B')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firmware',
            name='version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='firmware',
            unique_together={('device_type', 'version')},
        ),
    ]
