# Generated by Django 5.1 on 2024-10-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0005_machine_asset_name_machine_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('serialnumber', models.CharField(max_length=100, unique=True)),
                ('datesold', models.DateField(blank=True, null=True)),
                ('dateinservice', models.DateField(blank=True, null=True)),
                ('assetstatus', models.CharField(max_length=100)),
                ('assetname', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmware.customer')),
            ],
        ),
    ]
