# Generated by Django 5.1.2 on 2024-10-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0006_customer_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
