# Generated by Django 5.1.2 on 2024-11-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0008_remove_supportticket_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='product',
            field=models.CharField(default='Unknown Product', max_length=255),
        ),
    ]
